#include "UI.h"
#include "Container/Array.h"
#include "Container/HashMap.h"
#include "Container/String.h"
#include "Font/FontData.h"
#include "Input.h"
#include "Math/Math.h"
#include "Platform.h"
#include "Renderer2D.h"
#include "Texture.h"

#include <cmath>

#define STB_TRUETYPE_IMPLEMENTATION
#include "ThirdParty/StbTruetype.h"

namespace Aether::Engine::UI {

namespace {

Theme gTheme;
Renderer2D* gCurrentRenderer = nullptr;

constexpr u32 ATLAS_CELL = 44;
constexpr u32 ATLAS_COLS = 32;
constexpr u32 ATLAS_ROWS = 32;
constexpr u32 ATLAS_WIDTH = ATLAS_COLS * ATLAS_CELL;
constexpr u32 ATLAS_HEIGHT = ATLAS_ROWS * ATLAS_CELL;
constexpr u32 ATLAS_FONT_PX = 30;
constexpr u32 ATLAS_PAD = (ATLAS_CELL - ATLAS_FONT_PX) / 2;

constexpr i32 LAYER_FLASH = 38;

struct GlyphInfo
{
    u32 UvX = 0;
    u32 UvY = 0;
    u32 BbX = 0;
    u32 BbY = 0;
    u32 BbW = 0;
    u32 BbH = 0;
    u32 Advance = 0;
};

//
// Font rasterization. stb_truetype walks the embedded subset (Font/FontData.h,
// Noto Sans SC Bold, regenerated by Tools/GenFont.py) and emits 8-bit coverage
// bitmaps. The same bytes and the same code path run on every platform, so
// glyphs are pixel-identical on Win32 and Web.
//
stbtt_fontinfo sFontInfo;
bool sFontReady = false;
f32 sFontScale = 0.0f;
u8 sCoverageLut[256];

bool InitFont()
{
    if (sFontReady) return true;
    if (kFontDataSize == 0) return false;
    const int offset = stbtt_GetFontOffsetForIndex(kFontData, 0);
    if (offset < 0) return false;
    if (!stbtt_InitFont(&sFontInfo, kFontData, offset)) return false;

    sFontScale = stbtt_ScaleForMappingEmToPixels(&sFontInfo, (f32)ATLAS_FONT_PX);
    // Gamma-boost the coverage so thin strokes stay solid when the atlas is
    // minified (HUD labels draw at ~0.4x); unhinted antialiasing otherwise
    // smears narrow stems like 'I' into invisibility.
    for (u32 i = 0; i < 256; i++)
    {
        sCoverageLut[i] = (u8)(255.0f * powf((f32)i / 255.0f, 0.7f) + 0.5f);
    }
    sFontReady = true;
    return true;
}

// UTF-8 -> codepoints. UI text is BMP-range; astral code points decode to one
// u32 each and simply miss the atlas if not in the subset.
Array<u32> ToCodepoints(const char* text)
{
    Array<u32> out;
    if (!text || !*text) return out;

    const u8* p = (const u8*)text;
    while (*p)
    {
        u8 c = p[0];
        u32 cp = 0xFFFD;
        u32 extra = 0;
        if (c < 0x80)
        {
            cp = c;
        }
        else if ((c & 0xE0) == 0xC0)
        {
            cp = c & 0x1Fu;
            extra = 1;
        }
        else if ((c & 0xF0) == 0xE0)
        {
            cp = c & 0x0Fu;
            extra = 2;
        }
        else if ((c & 0xF8) == 0xF0)
        {
            cp = c & 0x07u;
            extra = 3;
        }

        bool valid = extra > 0;
        for (u32 i = 0; i < extra; i++)
        {
            u8 cc = p[1 + i];
            if ((cc & 0xC0) != 0x80)
            {
                valid = false;
                break;
            }
            cp = (cp << 6) | (cc & 0x3Fu);
        }
        if (extra && !valid) cp = 0xFFFD;

        out.Add(cp);
        p += 1 + extra;
    }
    return out;
}

class EmbeddedBackend : public Backend
{
public:
    void SetText(const char* element, const char* text) override
    {
        mTextMap.FindOrAdd(element) = text;
    }
    void SetVisible(const char* element, bool visible) override
    {
        mVisibleMap.FindOrAdd(element) = visible;
    }
    void SetFill(const char* element, f32 ratio) override
    {
        mFillMap.FindOrAdd(element) = ratio;
    }
    void Flash(const char* text, f32 duration) override
    {
        mFlashText = text;
        mFlashStart = Aether::Platform::NowSeconds();
        mFlashDuration = duration > 0.0f ? duration : 1.5f;
    }

    const char* GetText(const char* key, const char* fallback) override
    {
        const String* found = mTextMap.Find(key);
        return found ? found->CStr() : fallback;
    }
    bool IsVisible(const char* key, bool fallback) override
    {
        const bool* found = mVisibleMap.Find(key);
        return found ? *found : fallback;
    }
    f32 GetFill(const char* key, f32 fallback) override
    {
        const f32* found = mFillMap.Find(key);
        return found ? *found : fallback;
    }

    void Draw(Renderer2D* renderer) override
    {
        if (!renderer || !renderer->Device()) return;
        EnsureAssets(renderer);
        if (!mAtlas) return;

        if (!mFlashText.IsEmpty())
        {
            double now = Aether::Platform::NowSeconds();
            double fade = now - mFlashStart;
            double total = mFlashDuration + 0.5;
            if (fade < total)
            {
                f32 alpha = fade < mFlashDuration
                                ? 1.0f
                                : (f32)(1.0 - (fade - mFlashDuration) / 0.5);
                const char* flash = mFlashText.CStr();
                f32 halfW = 360.0f * renderer->Aspect();
                DrawTextScreen(renderer, flash, halfW, 274.0f, 38.0f, 6.0f, Math::Color{1.0f, 0.86f, 0.47f, alpha * 0.8f},
                               LAYER_FLASH, true, 0.4f);
                DrawTextScreen(renderer, flash, halfW, 274.0f, 38.0f, 6.0f, Math::Color{1.0f, 1.0f, 1.0f, alpha},
                               LAYER_FLASH, true, 0.0f);
            }
            else
            {
                mFlashText.Clear();
            }
        }
    }

    void DrawRectScreen(Renderer2D* renderer, const Rect& r, const Math::Color& col, i32 layer,
                        RHI::BlendMode blend = RHI::BlendMode::Alpha)
    {
        if (!renderer || !renderer->Device() || r.W <= 0.0f || r.H <= 0.0f) return;
        EnsureAssets(renderer);
        if (!mSolid) return;

        f32 halfH = 360.0f;
        f32 halfW = halfH * renderer->Aspect();
        Math::Vec2 cam = renderer->GetCamera().Position;
        f32 sx = (r.X - halfW) + cam.x + r.W * 0.5f;
        f32 sy = (r.Y - halfH) + cam.y + r.H * 0.5f;

        renderer->Sprites().Add(mSolid, {sx, sy}, {r.W, r.H}, col, 0.0f, layer, blend);
    }

    void DrawTextScreen(Renderer2D* renderer, const char* text, f32 screenX, f32 screenY,
                        f32 px, f32 spacing, const Math::Color& col, i32 layer, bool centered, f32 glow)
    {
        if (!renderer || !renderer->Device() || !text || !*text) return;
        EnsureAssets(renderer);
        if (!mAtlas) return;

        Array<u32> cps = ToCodepoints(text);
        if (cps.IsEmpty()) return;

        for (u32 cp : cps)
        {
            EnsureGlyph(renderer->Device(), cp);
        }

        if (mAtlasDirty)
        {
            mAtlas = MakeTexture(renderer->Device(), ATLAS_WIDTH, ATLAS_HEIGHT,
                                 [this](u32 x, u32 y, u8 out[4])
                                 {
                                     u32 idx = (y * ATLAS_WIDTH + x) * 4;
                                     out[0] = mRgba[idx + 0];
                                     out[1] = mRgba[idx + 1];
                                     out[2] = mRgba[idx + 2];
                                     out[3] = mRgba[idx + 3];
                                 });
            mAtlasDirty = false;
        }

        f32 halfH = 360.0f;
        f32 halfW = halfH * renderer->Aspect();
        Math::Vec2 cam = renderer->GetCamera().Position;
        f32 worldX = (screenX - halfW) + cam.x;
        f32 worldY = (screenY - halfH) + cam.y;

        f32 scale = px / (f32)ATLAS_FONT_PX;
        f32 total = Measure(text, px, spacing);
        f32 x = centered ? worldX - total * 0.5f : worldX;
        f32 y = worldY;

        f32 inkTop = 1e30f, inkBottom = -1e30f;
        for (u32 cp : cps)
        {
            GlyphInfo* g = mGlyphMap.Find(cp);
            if (!g) continue;
            if (g->BbW == 0 || g->BbH == 0) continue;
            if ((f32)g->BbY < inkTop) inkTop = (f32)g->BbY;
            if ((f32)(g->BbY + g->BbH) > inkBottom) inkBottom = (f32)(g->BbY + g->BbH);
        }
        f32 inkCenter = (inkTop + inkBottom) * 0.5f;

        for (u32 cp : cps)
        {
            GlyphInfo* g = mGlyphMap.Find(cp);
            if (g)
            {
                if (g->BbW > 0 && g->BbH > 0)
                {
                    f32 xMidOrig = (f32)g->BbX + (f32)g->BbW * 0.5f;
                    f32 yMidOrig = (f32)g->BbY + (f32)g->BbH * 0.5f;
                    f32 cx = x + xMidOrig * scale;
                    f32 cy = y + (yMidOrig - inkCenter) * scale;
                    f32 w = (f32)g->BbW * scale;
                    f32 h = (f32)g->BbH * scale;

                    f32 u0 = (f32)(g->UvX + g->BbX) / (f32)ATLAS_WIDTH;
                    f32 v0 = (f32)(g->UvY + g->BbY) / (f32)ATLAS_HEIGHT;
                    f32 u1 = u0 + (f32)g->BbW / (f32)ATLAS_WIDTH;
                    f32 v1 = v0 + (f32)g->BbH / (f32)ATLAS_HEIGHT;

                    if (glow > 0.0f && mGlow)
                    {
                        Math::Color glowCol = col;
                        glowCol.a = glow * col.a * 0.4f;
                        renderer->Sprites().AddUv(mAtlas, {u0, v0}, {u1, v1}, {cx, cy}, {w * 1.3f, h * 1.3f},
                                                  glowCol, 0.0f, layer - 1, RHI::BlendMode::Additive);
                    }

                    renderer->Sprites().AddUv(mAtlas, {u0, v0}, {u1, v1}, {cx, cy}, {w, h},
                                              col, 0.0f, layer, RHI::BlendMode::Alpha);
                }
                x += (f32)g->Advance * scale + spacing;
            }
            else
            {
                x += px * 0.6f + spacing;
            }
        }
    }

    f32 Measure(const char* text, f32 px, f32 spacing)
    {
        Array<u32> cps = ToCodepoints(text);
        if (cps.IsEmpty()) return 0.0f;

        f32 scale = px / (f32)ATLAS_FONT_PX;
        f32 total = 0.0f;
        u32 n = 0;
        for (u32 cp : cps)
        {
            GlyphInfo* g = mGlyphMap.Find(cp);
            if (g)
            {
                total += (f32)g->Advance * scale;
            }
            else
            {
                total += (cp > 128 ? px * 0.95f : px * 0.55f);
            }
            n++;
        }
        if (n > 1) total += spacing * (f32)(n - 1);
        return total;
    }

private:
    void EnsureAssets(Renderer2D* renderer)
    {
        if (mAtlasBuilt) return;
        if (!InitFont()) return;
        BuildAtlas(renderer->Device());
        mSolid = MakeSolidTexture(renderer->Device(), 4, 4, {1.0f, 1.0f, 1.0f, 1.0f});
        mGlow = MakeGlowTexture(renderer->Device(), 256);
        mAtlasBuilt = true;
    }

    bool BuildAtlas(RHI::RHIDevice* device)
    {
        mRgba.Clear();
        mRgba.Resize(ATLAS_WIDTH * ATLAS_HEIGHT * 4);
        for (u32 i = 0; i < mRgba.Count(); i++)
        {
            mRgba[i] = 0;
        }

        // Pre-populate ASCII printable range (32..126)
        for (u32 i = 0; i < 95; i++)
        {
            EnsureGlyph(device, i + 32);
        }

        mAtlas = MakeTexture(device, ATLAS_WIDTH, ATLAS_HEIGHT,
                             [this](u32 x, u32 y, u8 out[4])
                             {
                                 u32 idx = (y * ATLAS_WIDTH + x) * 4;
                                 out[0] = mRgba[idx + 0];
                                 out[1] = mRgba[idx + 1];
                                 out[2] = mRgba[idx + 2];
                                 out[3] = mRgba[idx + 3];
                             });

        mAtlasDirty = false;
        return mAtlas.IsValid();
    }

    void EnsureGlyph(RHI::RHIDevice* device, u32 cp)
    {
        (void)device;
        if (mGlyphMap.Find(cp)) return;
        if (mNextSlot >= ATLAS_COLS * ATLAS_ROWS) return;
        u32 slot = mNextSlot++;
        u32 x0 = (slot % ATLAS_COLS) * ATLAS_CELL;
        u32 y0 = (slot / ATLAS_COLS) * ATLAS_CELL;

        GlyphInfo g;
        g.UvX = x0;
        g.UvY = y0;

        int glyphIndex = stbtt_FindGlyphIndex(&sFontInfo, (int)cp);
        if (glyphIndex > 0)
        {
            int bw = 0, bh = 0, xoff = 0, yoff = 0;
            unsigned char* bmp = stbtt_GetGlyphBitmap(&sFontInfo, sFontScale, sFontScale,
                                                      glyphIndex, &bw, &bh, &xoff, &yoff);
            int advanceLu = 0, lsbLu = 0;
            stbtt_GetGlyphHMetrics(&sFontInfo, glyphIndex, &advanceLu, &lsbLu);
            g.Advance = (u32)((f32)advanceLu * sFontScale + 0.5f);

            if (bmp && bw > 0 && bh > 0)
            {
                // Pen-metric invariant: the draw code places ink at
                // pen + BbX*scale, so the blit must honor the glyph's left
                // bearing (xoff) exactly - centering horizontally would shift
                // narrow glyphs right by half the cell. Vertical placement is
                // free (DrawTextScreen re-centers ink per string).
                const i32 bx = 2 + xoff;
                const i32 by = (i32)((ATLAS_CELL - (u32)bh) / 2);

                u32 minX = ATLAS_CELL, maxX = 0, minY = ATLAS_CELL, maxY = 0;
                for (int row = 0; row < bh; row++)
                {
                    const int py = by + row;
                    if (py < 0 || py >= (i32)ATLAS_CELL) continue;
                    const unsigned char* src = bmp + row * bw;
                    for (int col = 0; col < bw; col++)
                    {
                        const int px = bx + col;
                        if (px < 0 || px >= (i32)ATLAS_CELL) continue;
                        const u8 a = sCoverageLut[src[col]];
                        u32 idx = ((y0 + (u32)py) * ATLAS_WIDTH + x0 + (u32)px) * 4;
                        mRgba[idx + 0] = 255;
                        mRgba[idx + 1] = 255;
                        mRgba[idx + 2] = 255;
                        mRgba[idx + 3] = a;
                        if (a > 0)
                        {
                            const u32 cx = (u32)px, cy = (u32)py;
                            if (cx < minX) minX = cx;
                            if (cx > maxX) maxX = cx;
                            if (cy < minY) minY = cy;
                            if (cy > maxY) maxY = cy;
                        }
                    }
                }
                if (maxX >= minX && maxY >= minY)
                {
                    g.BbX = minX;
                    g.BbY = minY;
                    g.BbW = maxX - minX + 1;
                    g.BbH = maxY - minY + 1;
                }
                stbtt_FreeBitmap(bmp, nullptr);
            }
        }
        else
        {
            // Not in the subset: keep a sane advance so strings keep flowing.
            g.Advance = ATLAS_FONT_PX / 2;
        }

        mGlyphMap.Add(cp, g);
        mAtlasDirty = true;
    }

    HashMap<String, String> mTextMap;
    HashMap<String, bool> mVisibleMap;
    HashMap<String, f32> mFillMap;

    String mFlashText;
    double mFlashStart = 0.0;
    f32 mFlashDuration = 1.5f;

    RefPtr<RHI::RHITexture> mAtlas;
    RefPtr<RHI::RHITexture> mSolid;
    RefPtr<RHI::RHITexture> mGlow;
    Array<u8> mRgba;
    HashMap<u32, GlyphInfo> mGlyphMap;
    u32 mNextSlot = 0;
    bool mAtlasDirty = false;
    bool mAtlasBuilt = false;
};

EmbeddedBackend sUiBackend;

Backend* sBackend = nullptr;

Backend* ActiveBackend()
{
    if (sBackend) return sBackend;
    return &sUiBackend;
}

} // namespace

void Init()
{
    InitFont();
}

void SetBackend(Backend* backend)
{
    sBackend = backend;
}

Theme& GetTheme()
{
    return gTheme;
}

void BeginFrame(Renderer2D* renderer)
{
    gCurrentRenderer = renderer;
}

void EndFrame()
{
    gCurrentRenderer = nullptr;
}

void DrawRect(const Rect& r, const Math::Color& col, i32 layer, RHI::BlendMode blend)
{
    sUiBackend.DrawRectScreen(gCurrentRenderer, r, col, layer, blend);
}

void DrawRectOutline(const Rect& r, f32 thickness, const Math::Color& col, i32 layer)
{
    if (r.W <= 0.0f || r.H <= 0.0f || thickness <= 0.0f) return;
    // Top, bottom, left, right borders
    DrawRect({r.X, r.Y, r.W, thickness}, col, layer);
    DrawRect({r.X, r.Y + r.H - thickness, r.W, thickness}, col, layer);
    DrawRect({r.X, r.Y + thickness, thickness, r.H - thickness * 2.0f}, col, layer);
    DrawRect({r.X + r.W - thickness, r.Y + thickness, thickness, r.H - thickness * 2.0f}, col, layer);
}

void DrawPanel(const Rect& r, const char* title, const Math::Color* bg, const Math::Color* border, i32 layer)
{
    Math::Color bgColor = bg ? *bg : gTheme.BgPanel;
    Math::Color borderColor = border ? *border : gTheme.Border;

    // Body
    DrawRect(r, bgColor, layer);
    DrawRectOutline(r, 1.5f, borderColor, layer);

    // Title bar if present
    if (title && *title)
    {
        f32 titleH = 26.0f;
        Rect headerRect = {r.X, r.Y, r.W, titleH};
        DrawRect(headerRect, gTheme.BgCard, layer + 1);
        DrawRectOutline(headerRect, 1.0f, gTheme.Border, layer + 1);
        DrawText(title, r.X + 10.0f, r.Y + 13.0f, 13.0f, 1.0f, gTheme.TextAccent, layer + 2, false, 0.2f);
    }
}

void DrawText(const char* text, f32 x, f32 y, f32 px, f32 spacing,
              const Math::Color& col, i32 layer, bool centered, f32 glow)
{
    sUiBackend.DrawTextScreen(gCurrentRenderer, text, x, y, px, spacing, col, layer, centered, glow);
}

f32 Measure(const char* text, f32 px, f32 spacing)
{
    return sUiBackend.Measure(text, px, spacing);
}

bool Button(const char* label, const Rect& r, bool active, i32 layer)
{
    Math::Vec2 mpos = Input::MousePos();
    bool hovered = r.Contains(mpos);
    bool clicked = hovered && Input::WasMousePressed(MouseButton::Left);

    Math::Color bg = active ? gTheme.BgActive : (hovered ? gTheme.BgHover : gTheme.BgCard);
    Math::Color border = active ? gTheme.BorderActive : (hovered ? gTheme.BorderBright : gTheme.Border);
    Math::Color textCol = active ? gTheme.TextPrimary : (hovered ? gTheme.TextPrimary : gTheme.TextSecondary);

    DrawRect(r, bg, layer);
    DrawRectOutline(r, active || hovered ? 2.0f : 1.0f, border, layer);
    if (hovered)
    {
        DrawRect(r, Math::Color{0.2f, 0.8f, 1.0f, 0.15f}, layer + 1, RHI::BlendMode::Additive);
    }

    Math::Vec2 c = r.Center();
    DrawText(label, c.x, c.y, 14.0f, 1.0f, textCol, layer + 2, true, hovered ? 0.3f : 0.0f);
    return clicked;
}

bool IconButton(const char* label, const char* iconTxt, const Rect& r, bool active, i32 layer)
{
    Math::Vec2 mpos = Input::MousePos();
    bool hovered = r.Contains(mpos);
    bool clicked = hovered && Input::WasMousePressed(MouseButton::Left);

    Math::Color bg = active ? gTheme.BgActive : (hovered ? gTheme.BgHover : gTheme.BgCard);
    Math::Color border = active ? gTheme.BorderActive : (hovered ? gTheme.BorderBright : gTheme.Border);

    DrawRect(r, bg, layer);
    DrawRectOutline(r, 1.5f, border, layer);

    if (iconTxt && *iconTxt)
    {
        DrawText(iconTxt, r.X + 8.0f, r.Y + r.H * 0.5f, 15.0f, 0.0f, gTheme.TextAccent, layer + 2, false);
    }
    if (label && *label)
    {
        f32 tx = (iconTxt && *iconTxt) ? r.X + 28.0f : r.X + 8.0f;
        DrawText(label, tx, r.Y + r.H * 0.5f, 13.0f, 0.5f, gTheme.TextPrimary, layer + 2, false);
    }
    return clicked;
}

bool ToggleButton(const char* label, bool* value, const Rect& r, i32 layer)
{
    bool current = value ? *value : false;
    if (Button(label, r, current, layer))
    {
        if (value) *value = !*value;
        return true;
    }
    return false;
}

void ProgressBar(const Rect& r, f32 ratio, const Math::Color& fillCol, const Math::Color* bgCol, const char* label, i32 layer)
{
    Math::Color bg = bgCol ? *bgCol : gTheme.BgDark;
    DrawRect(r, bg, layer);
    DrawRectOutline(r, 1.0f, gTheme.Border, layer);

    f32 clamped = Math::Clamp(ratio, 0.0f, 1.0f);
    if (clamped > 0.0f)
    {
        Rect fillRect = {r.X + 1.0f, r.Y + 1.0f, (r.W - 2.0f) * clamped, r.H - 2.0f};
        DrawRect(fillRect, fillCol, layer + 1);
        Math::Color glow = fillCol;
        glow.a = 0.35f;
        DrawRect(fillRect, glow, layer + 1, RHI::BlendMode::Additive);
    }

    if (label && *label)
    {
        Math::Vec2 c = r.Center();
        DrawText(label, c.x, c.y, 11.0f, 0.5f, gTheme.TextPrimary, layer + 2, true);
    }
}

void StatCard(const Rect& r, const char* title, const char* value, const char* subtitle, const Math::Color* accent, i32 layer)
{
    Math::Color acc = accent ? *accent : gTheme.AccentCyan;
    DrawPanel(r, nullptr, &gTheme.BgCard, &gTheme.Border, layer);

    // Left accent bar
    DrawRect({r.X, r.Y, 3.0f, r.H}, acc, layer + 1);

    if (title)
    {
        DrawText(title, r.X + 10.0f, r.Y + 12.0f, 11.0f, 0.5f, gTheme.TextMuted, layer + 2);
    }
    if (value)
    {
        DrawText(value, r.X + 10.0f, r.Y + 28.0f, 18.0f, 1.0f, gTheme.TextPrimary, layer + 2, false, 0.2f);
    }
    if (subtitle)
    {
        DrawText(subtitle, r.X + 10.0f, r.Y + r.H - 10.0f, 10.0f, 0.0f, acc, layer + 2);
    }
}

void Badge(const char* text, f32 x, f32 y, const Math::Color& bg, const Math::Color& fg, i32 layer)
{
    f32 w = Measure(text, 11.0f, 0.0f) + 12.0f;
    f32 h = 18.0f;
    Rect r = {x, y - h * 0.5f, w, h};
    DrawRect(r, bg, layer);
    DrawRectOutline(r, 1.0f, fg, layer);
    DrawText(text, r.Center().x, r.Center().y, 11.0f, 0.0f, fg, layer + 1, true);
}

void Tooltip(const char* text, const Math::Vec2& pos, i32 layer)
{
    if (!text || !*text) return;
    f32 w = Measure(text, 12.0f, 0.5f) + 16.0f;
    f32 h = 24.0f;
    Rect r = {pos.x + 12.0f, pos.y + 12.0f, w, h};
    DrawRect(r, gTheme.BgDark, layer);
    DrawRectOutline(r, 1.0f, gTheme.BorderBright, layer);
    DrawText(text, r.Center().x, r.Center().y, 12.0f, 0.5f, gTheme.TextPrimary, layer + 1, true);
}

void Flash(const char* text, f32 duration)
{
    ActiveBackend()->Flash(text, duration);
}

void SetText(const char* element, const char* text)
{
    ActiveBackend()->SetText(element, text);
}

void SetVisible(const char* element, bool visible)
{
    ActiveBackend()->SetVisible(element, visible);
}

void SetFill(const char* element, f32 ratio)
{
    ActiveBackend()->SetFill(element, ratio);
}

const char* GetText(const char* element, const char* defaultValue)
{
    return ActiveBackend()->GetText(element, defaultValue);
}

bool Visible(const char* element, bool defaultValue)
{
    return ActiveBackend()->IsVisible(element, defaultValue);
}

f32 Fill(const char* element, f32 defaultValue)
{
    return ActiveBackend()->GetFill(element, defaultValue);
}

void Draw(Renderer2D* renderer)
{
    BeginFrame(renderer);
    ActiveBackend()->Draw(renderer);
    EndFrame();
}

}
