"""Generate the embedded UI font subset for the Aether engine.

Pipeline:
  1. Scan Source/ string literals for every non-ASCII character used by UI text
     (plus the printable ASCII range, always kept).
  2. Subset Noto Sans SC Bold (static 700, from @fontsource/noto-sans-sc woff2,
     OFL licensed) down to that character set.
  3. Emit:
       Source/Engine/Private/Font/NotoSansSC-Bold-Subset.ttf
       Source/Engine/Private/Font/FontData.h     (byte array, included by UI.cpp)
     and copy the OFL license next to them.

NOTE: adding new UI copy with new Chinese characters requires re-running this
script (Tools/GenFont.py), otherwise the new glyphs render as blanks.

Inputs (fetched into Tools/_fontwork/ by Tools/_fontwork/fetch.py):
  noto-chinese.woff2 - @fontsource/noto-sans-sc chinese-simplified 700 (covers
                       ASCII as well; latin woff2 not needed)
Requires: pip install fonttools brotli
"""

import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIRS = [ROOT / "Source" / "Demo", ROOT / "Source" / "Engine",
               ROOT / "Source" / "RHI", ROOT / "Source" / "Platform"]
WORK_WOFF2 = ROOT / "Tools" / "_fontwork" / "noto-chinese.woff2"
OFL_TXT = ROOT / "Tools" / "_fontwork" / "OFL.txt"
OUT_DIR = ROOT / "Source" / "Engine" / "Private" / "Font"
OUT_TTF = OUT_DIR / "NotoSansSC-Bold-Subset.ttf"
OUT_HEADER = OUT_DIR / "FontData.h"
OUT_LICENSE = OUT_DIR / "OFL.txt"
BYTES_PER_LINE = 24


def scan_used_characters():
    chars = set(chr(c) for c in range(0x20, 0x7F))  # printable ASCII, always kept
    pattern = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
    exts = {".h", ".cpp"}
    files = [p for d in SOURCE_DIRS if d.exists() for p in d.rglob("*") if p.suffix in exts]
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        for literal in pattern.findall(text):
            for ch in literal:
                if ord(ch) > 0x7E or ord(ch) < 0x20:
                    chars.add(ch)
    return chars, len(files)


def main():
    chars, file_count = scan_used_characters()
    unicodes = sorted(ord(c) for c in chars)
    non_ascii = [c for c in chars if ord(c) > 0x7E]
    print("scanned %d files: %d unique chars (%d non-ASCII)" % (file_count, len(chars), len(non_ascii)))

    font = TTFont(str(WORK_WOFF2))  # woff2 decoded via brotli; static weight 700
    cmap = font.getBestCmap()
    missing = [c for c in chars if ord(c) not in cmap]
    if missing:
        sys.exit("ERROR: %d chars missing from source font: %s" % (len(missing), "".join(missing)))

    options = subset.Options()
    options.layout_features = []      # UI renders glyph-by-glyph; no shaping needed
    options.hinting = False
    options.drop_tables += ["GSUB", "GPOS", "BASE", "vhea", "vmtx"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    font.flavor = None                # emit plain TTF (stb_truetype input)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    font.save(str(OUT_TTF))
    data = OUT_TTF.read_bytes()
    print("subset font: %s (%d bytes)" % (OUT_TTF, len(data)))

    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))
    header = """// GENERATED by Tools/GenFont.py - do not edit by hand.
// Noto Sans SC Bold subset (c) 2014-2021 Adobe, SIL OFL 1.1 - see Font/OFL.txt.
// Re-run Tools/GenFont.py after adding UI text with new characters.
#pragma once

#include "Core.h"

namespace Aether::Engine {

inline constexpr unsigned char kFontData[] = {
%s
};
inline constexpr unsigned int kFontDataSize = sizeof(kFontData);

} // namespace Aether::Engine
""" % ("\n".join(lines))
    OUT_HEADER.write_text(header, encoding="utf-8", newline="\n")
    print("wrote %s" % OUT_HEADER)

    if OFL_TXT.exists():
        OUT_LICENSE.write_bytes(OFL_TXT.read_bytes())
        print("copied license -> %s" % OUT_LICENSE)


if __name__ == "__main__":
    sys.exit(main())
